#!/bin/bash

# shellcheck source=/dev/null
source "$(dirname "$0")/common/base.sh"

brew_prefix="$(brew --prefix)"

while [[ "$(basename -- "$1")" = "${shim_basename:?}" ]]; do
  shift
done

exec "$brew_prefix/opt/ccache/bin/ccache" "$@"
